#!/bin/tcsh
#Checks the uname information and starts up the
#correct 32 or 64 bit Viewer interface

set LPATH=/opt/MouseAtlas/lib/WlzWarp
setenv COIN_FULL_INDIRECT_RENDERING 1
setenv SO_DRAGGER_DIR $LPATH/draggers

if (`uname -i` == "x86_64" && $1 != "32" ) then
  echo Starting 64 bit viewer
  setenv LD_LIBRARY_PATH $LPATH/lib64:$LD_LIBRARY_PATH
  set APP=Viewer
else
  echo Starting 32 bit viewer
  setenv LD_LIBRARY_PATH $LPATH/lib32:$LD_LIBRARY_PATH
  set APP=Viewer32
endif

nohup $LPATH/$APP &
