#if defined(__GNUC__)
#ident "MRC HGU $Id$"
#else
#if defined(__SUNPRO_C) || defined(__SUNPRO_CC)
#pragma ident "MRC HGU $Id$"
#else
static char _WoolzDynObject_cpp[] = "MRC HGU $Id$";
#endif
#endif
/*!
* \file         WoolzDynWarpedObject .cpp
* \author       Zsolt Husz
* \date         June 2009
* \version      $Id$
* \par
* Address:
*               MRC Human Genetics Unit,
*               Western General Hospital,
*               Edinburgh, EH4 2XU, UK.
* \par
* Copyright (C) 2008 Medical research Council, UK.
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be
* useful but WITHOUT ANY WARRANTY; without even the implied
* warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
* PURPOSE.  See the GNU General Public License for more
* details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA  02110-1301, USA.
* \brief        Dynamicaly generated Woolz object class
* \ingroup      Control
*
*/
#include "WoolzDynWarpedObject.h"
#include "LandmarkModel.h"
#include "ObjectListModel.h"
#include "WarperConfig.h"
#include <QtXml/QDomElement>
#include <QtXml/QXmlStreamWriter>

const char* WoolzDynWarpedObject::xmlTag = "WarpedObject";

WoolzDynWarpedObject ::WoolzDynWarpedObject (ObjectListModel * objectListModel, LandmarkModel *landmarkModel) :
       WoolzDynObject(objectListModel), m_landmarkModel(landmarkModel), m_outdatedWarp(true)  {
  connect(m_landmarkModel, SIGNAL(removedLandmark(int)), this, SLOT(updateWarp()));
  connect(m_landmarkModel, SIGNAL(addedLandmarkPair(int)), this, SLOT(updateWarp()));
  connect(m_landmarkModel, SIGNAL(movedSourceLandmark(const int, const WlzDVertex3)),
    this, SLOT(updateWarp()));
  connect(m_landmarkModel, SIGNAL(movedTargetLandmark(const int, const WlzDVertex3)),
    this, SLOT(updateWarp()));
  connect(m_landmarkModel, SIGNAL(warpingChanged()),
    this, SLOT(updateWarp()));

  /*connect(m_objectListModel, SIGNAL(replaceWarpMesh(WoolzObject *)),
    this, SLOT(update()));*/
}

WoolzDynWarpedObject ::~WoolzDynWarpedObject () {
}

void WoolzDynWarpedObject ::setTypeFromSource () {
  WoolzObject *srcObj = sourceObj();
  if (srcObj)
     changeWoolzObjectType(((srcObj->type())==source)  ? target : source);
}

void WoolzDynWarpedObject ::warp () {
  const WlzInterpolationType interp = WLZ_INTERPOLATION_NEAREST;
  WlzErrorNum errNum = WLZ_ERR_NONE;
  WlzBasisFnTransform *basisTr=NULL;
  WlzTransform transform;
  WoolzObject *srcObj = sourceObj();
  WlzFreeObj(m_obj);
  m_obj = NULL;

  //does object has a source object?
  if (!srcObj) {
    return;
  }

  statusChange("Warping " + m_name+ " started.", 0);

  if (!m_landmarkModel->isValidLandmakSet()) {
     m_obj = WlzAssignObject( srcObj->getObj(), &errNum );
     statusChange("Warping " + m_name+ " failed: invalid landmarks.", 0);
     return ;
  }

  WoolzObject *meshObj = m_objectListModel->getMeshObject();
  if (!meshObj) {
     m_obj = WlzAssignObject( srcObj->getObj(), &errNum );
     statusChange("Warping " + m_name+ " failed: no mesh.", 0);
     return ;
  }

  bool isSourceMesh = meshObj->type() == WoolzObject::source;
  bool isSourceSourceObj = srcObj->type() == WoolzObject::source;
  bool direct  = isSourceMesh == isSourceSourceObj;

  // create basis transform by generated by the landmarks
  if (errNum == WLZ_ERR_NONE) {
//   transform.obj = WlzAssignObject(meshObj->getObj(), & errNum);
}
  transform.obj = NULL;
  if (errNum == WLZ_ERR_NONE) {
      transform.obj = WlzAssignObject(meshObj->getObj(), NULL);
      basisTr = m_landmarkModel->getBasisTransform(&transform, errNum, isSourceMesh);
  }
  if (errNum == WLZ_ERR_NONE) {
    if (direct && !srcObj->isMesh()) {

      // temporary solution for creating index value of the object
      WlzValues     values;

      WlzFreeObj(transform.obj);
      transform.obj = WlzAssignObject(
                         WlzMakeMain(srcObj->is3D() ? WLZ_CMESH_3D : WLZ_CMESH_2D, meshObj->getObj()->domain, values, NULL, NULL, &errNum), NULL);
      if(errNum == WLZ_ERR_NONE)
       {
          int dim =meshObj->is3D() ? 3: 2;
          values.x = WlzMakeIndexedValues(transform.obj, 1, &dim, WLZ_GREY_DOUBLE,
                                         WLZ_VALUE_ATTACH_NOD, &errNum);
       }
       if(errNum == WLZ_ERR_NONE)
       {
         transform.obj->values = WlzAssignValues(values, NULL);
         //errNum = WlzIndexedValuesSet(mObj, dim * sizeof(double), (void *)dsp);
       }

       basisTr = m_landmarkModel->getBasisTransform(&transform, errNum, isSourceMesh);

       errNum = WlzBasisFnSetCMesh(transform.obj, basisTr);

    } else {
      if (errNum == WLZ_ERR_NONE) {
           WlzFreeObj(transform.obj);
           WlzCMeshP     dirMesh;
           dirMesh.m3=transform.obj->domain.cm3;
           transform.obj = WlzBasisFnInvertAndSetCMesh(basisTr, dirMesh, &errNum);
       }
       if (errNum == WLZ_ERR_NONE && srcObj->isMesh()) {          // mesh transform
            WlzValues     val;
            val.core = NULL;
            m_obj = WlzMakeMain(srcObj->is3D() ? WLZ_CMESH_3D : WLZ_CMESH_2D, transform.obj->domain, val, NULL, NULL, &errNum);
       }
    }
  }
  if (errNum == WLZ_ERR_NONE) {
    if (!srcObj->isMesh())
      m_obj  = WlzCMeshTransformObj( srcObj->getObj(), transform.obj, interp, &errNum);  //volume transform
  }
  WlzFreeObj(transform.obj);
  if (errNum == WLZ_ERR_NONE) {
      statusChange("Warping " + m_name+ " done.", 0);
      saveUsedParameters();
      m_obj = WlzAssignObject( m_obj, &errNum);
  }
  else {
      if (m_obj)
        WlzFreeObj(m_obj);
      m_obj = WlzAssignObject( srcObj->getObj(), &errNum );
      statusChange("Warping " + m_name+ " failed.", 0);
      emit invalidWarping();
  }
}

void WoolzDynWarpedObject ::doUpdate ( ) {
  if (!sourceObj())
      return;
  warp();
  setTypeFromSource();
  setupTransferFunction();
  emit objectChanged();
}

QString WoolzDynWarpedObject::notes ( )  {
  QString notes = "Warped ";
  notes  += (type()==source) ? "source" : "target";
  notes += isMesh() ?" mesh" : " value";
  if (sourceObj())
    notes += " of " + sourceObj()->name();
  notes += m_autoUpdate ? " (autoupdate)" : " (no autoupdate)";
  return notes;
}

void WoolzDynWarpedObject::setupConnections(QObject *target) {
    WoolzDynObject::setupConnections(target);
    connect( target, SIGNAL(updateAllWarpedSignal()), this, SLOT(update()));
}

void WoolzDynWarpedObject::update ( bool force ) {
  if ((m_autoUpdate && config.globalAutoUpdate() && config.globalWarpUpdate() && needsUpdate()) || force) {
     removeCachedVisualisation();     doUpdate();
  }
}

bool WoolzDynWarpedObject::saveAsXml(QXmlStreamWriter *xmlWriter) {
  xmlWriter->writeStartElement(xmlTag);
  saveAsXmlProperties(xmlWriter);
  xmlWriter->writeEndElement();
  return true;
}

void WoolzDynWarpedObject::updateWarp() {
    m_outdatedWarp = true;
    update();
}

bool  WoolzDynWarpedObject::needsUpdate() {
    return m_outdatedWarp  || WoolzDynObject::needsUpdate();
}

void WoolzDynWarpedObject::saveUsedParameters() {
    m_outdatedWarp = false;
    WoolzDynObject::saveUsedParameters();
}
