#if defined(__GNUC__)
#ident "MRC HGU $Id$"
#else
#if defined(__SUNPRO_C) || defined(__SUNPRO_CC)
#pragma ident "MRC HGU $Id$"
#else
static char _WoolzDynObject_cpp[] = "MRC HGU $Id$";
#endif
#endif
/*!
* \file         WoolzDynWarpedObject.cpp
* \author       Zsolt Husz
* \date         June 2009
* \version      $Id$
* \par
* Address:
*               MRC Human Genetics Unit,
*               Western General Hospital,
*               Edinburgh, EH4 2XU, UK.
* \par
* Copyright (C) 2008 Medical research Council, UK.
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be
* useful but WITHOUT ANY WARRANTY; without even the implied
* warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
* PURPOSE.  See the GNU General Public License for more
* details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA  02110-1301, USA.
* \brief        Dynamicaly generated Woolz object class
* \ingroup      Control
*
*/
#include "WoolzDynWarpedObject.h"
#include "WoolzTransform.h"

#include "ObjectListModel.h"
#include "WarperConfig.h"
#include <QtXml/QDomElement>
#include <QtXml/QXmlStreamWriter>

const char* WoolzDynWarpedObject::xmlTag = "WarpedObject";

WoolzDynWarpedObject ::WoolzDynWarpedObject (ObjectListModel * objectListModel, WoolzTransform *woolzTransform) :
       WoolzDynObject(objectListModel), m_woolzTransform(woolzTransform), m_outdatedWarp(true) {
  connect(woolzTransform, SIGNAL(updated()), this, SLOT(updateWarp()));
}

WoolzDynWarpedObject ::~WoolzDynWarpedObject () {
}

void WoolzDynWarpedObject ::setTypeFromSource () {
  WoolzObject *srcObj = sourceObj();
  if (srcObj)
     changeWoolzObjectType(((srcObj->type())==source)  ? target : source);
}

void WoolzDynWarpedObject ::warp () {
  const WlzInterpolationType interp = WLZ_INTERPOLATION_NEAREST;
  WlzErrorNum errNum = WLZ_ERR_NONE;

  WoolzObject *srcObj = sourceObj();
  WlzFreeObj(m_obj);
  m_obj = NULL;

  //does object has a source object?
  if (!srcObj) {
    return;
  }

  statusChange("Warping " + m_name+ " started.", 0);

  //check for errors
  QString errorMsg;
  if (!m_woolzTransform->isReadyForWarp(errorMsg)) {
     m_obj = WlzAssignObject( srcObj->getObj(), &errNum );
     statusChange("Warping " + m_name+ " failed: " + errorMsg + ".", 0);
     return ;
  }

  // create basis transform by generated by the landmarks
  if (errNum == WLZ_ERR_NONE) {
  }
  if (errNum == WLZ_ERR_NONE) {
     if (!srcObj->isMesh())
        m_obj  = m_woolzTransform->Transform(srcObj, interp, &errNum);  //volume transform
      else
        m_obj  = m_woolzTransform->TransformedMesh();
  }
  //WlzFreeObj(transformObj);
  if (errNum == WLZ_ERR_NONE) {
      statusChange("Warping " + m_name+ " done.", 0);
      saveUsedParameters();
      m_obj = WlzAssignObject( m_obj, &errNum);
  }
  else {
      if (m_obj)
        WlzFreeObj(m_obj);
      m_obj = WlzAssignObject( srcObj->getObj(), &errNum );
      statusChange("Warping " + m_name+ " failed.", 0);
      emit invalidWarping();
  }
}

void WoolzDynWarpedObject ::doUpdate ( ) {
  if (!sourceObj())
      return;
  warp();
  setTypeFromSource();
  setupTransferFunction();
  emit objectChanged();
}

QString WoolzDynWarpedObject::notes ( )  {
  QString notes = "Warped ";
  notes  += (type()==source) ? "source" : "target";
  notes += isMesh() ?" mesh" : " value";
  if (sourceObj())
    notes += " of " + sourceObj()->name();
  notes += m_autoUpdate ? " (autoupdate)" : " (no autoupdate)";
  return notes;
}

void WoolzDynWarpedObject::setupConnections(QObject *target) {
    WoolzDynObject::setupConnections(target);
    connect( target, SIGNAL(updateAllWarpedSignal(bool)), this, SLOT(update(bool)));
}

void WoolzDynWarpedObject::update ( bool force ) {
  if ((m_autoUpdate && config.globalAutoUpdate() && config.globalWarpUpdate() && needsUpdate()) || force) {
     removeCachedVisualisation();     doUpdate();
  }
}

bool WoolzDynWarpedObject::saveAsXml(QXmlStreamWriter *xmlWriter) {
  xmlWriter->writeStartElement(xmlTag);
  saveAsXmlProperties(xmlWriter);
  xmlWriter->writeEndElement();
  return true;
}

void WoolzDynWarpedObject::updateWarp() {
    m_outdatedWarp = true;
    emit updated(false);
    update();
}

bool  WoolzDynWarpedObject::needsUpdate() {
    return m_outdatedWarp || WoolzDynObject::needsUpdate();
}

void WoolzDynWarpedObject::saveUsedParameters() {
    m_outdatedWarp = false;
    WoolzDynObject::saveUsedParameters();
}
