#!/bin/bash
# extract libraries used by warping from MA_HOME/lib and QTDIR/lib
# copylibs <list file> <new lib dir >

echo MA_HOME is set to $MA_HOME
echo QTDIR is set to $QTDIR

for  i in  $(cat $1)
do
  echo Copying from MA_HOME $i ...
  
  cp ${MA_HOME}/lib/$i $3 &>/dev/null 
  if [ $?  -ne 0 ]; then
     echo .......faild. copy from QTDIR.....
     cp ${QTDIR}/lib/$i $3  &>/dev/null
  fi
  if [ $? -ne 0 ]; then 
    echo  ...................................failed
  else
    echo  ...................................success
  fi
done
